version: "3.8"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=grocery_db
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grocery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
